dbframe -- an R to SQL interface

* Description
  This package is designed to simplify database queries in R.  It
  creates a new "dbframe" class that functions like a data frame, but
  is linked to a table, view, or query from a SQL database.  It also
  defines "insert" and "select" methods that essentially mimic the
  corresponding SQL statements but require much less typing.

  So far (as of [2011-12-01 Thu]), the library works with SQLite
  databases.  There is a general method to link with arbitrary
  database engines, but I have not run or tested it, so watch out.
  Joins have not been implemented yet, nor have other queries; but I
  hope to add them soon.
* Use
  I assume that you know how to load libraries in R.  If not, type
  '?library' at the R prompt and read the documentation.  dbframe is
  loaded as usual.  At the moment, it needs the RSQLite library to be
  installed as well, but that isn't listed as a formal dependency.
  See the package documentation (available as a pdf download from
  github) for details of the functions defined by this package.
* Installation
  Installation is a little trickier than it is for most R libraries;
  this package is a "literate program," meaning that the documentation
  and the code are marked up in the files "dbframe/webs/*.rnw".  The
  "noweb" program parses those files and 

  - writes the code to .R files in the folder "dbframe/R"
  - writes the documentation to .Rd files in the filder "dbframe/man"
  - writes the individual tests to .R files in the folder
    "dbframe/inst/tests"

  Just to emphasize this point: the .rnw files are *not* Sweave files;
  they're noweb files.  Noweb can be downloaded at:
  http://www.cs.tufts.edu/~nr/noweb/

  If you have noweb installed, typing 'make' will generate these files
  and then check the package for errors.  You may need to change some
  of the paths to binaries on your system.  Noweb just converts the
  .rnw files to .Rd files for the documentation, using the shell
  script provided in this package which is minor modification of the
  totex script provided by noweb.

  If you're just interested in trying out the package, it might be
  easiest to download a compressed archive of the full (post makefile)
  package from my website: http://www.econ.iastate.edu/~gcalhoun
